---
abstract: 'FillInForm with utf8 encoding'
author:
  - 'Masahiro Nagano <kazeburo@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.14.1, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-FillInForm-ForceUTF8
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  HTML::FillInForm::ForceUTF8:
    file: lib/HTML/FillInForm/ForceUTF8.pm
    version: 0.03
requires:
  Encode: 0
  HTML::FillInForm: 0
resources:
  bugtracker: https://github.com/kazeburo/HTML-FillInForm-ForceUTF8/issues
  homepage: https://github.com/kazeburo/HTML-FillInForm-ForceUTF8
  repository: git://github.com/kazeburo/HTML-FillInForm-ForceUTF8.git
version: 0.03
x_authority: cpan:KAZEBURO
